firstname = input("Enter First Name: " )
lastname = input("Enter Last Name: " )
Middlename = input("Middle Name: " )
Birthday = input("Enter Birthday: " )
Gender = input("Enter Gender: " )
Address = input("Enter Address: " )
Course = input("Enter Course: " )
YearLevel = input("Enter Year Level: " )

print("First Name: " + firstname)
print("Last Name: " + lastname)
print("Middle Name: " + Middlename)
print("Birthday: " + Birthday)
print("Gender: " + Gender)
print("Address: " + Address)
print("Course: " + Course)
print("Year level: " + YearLevel)
